apiVersion: v1
kind: Service
metadata:
  name: tf-idf-worker
  labels:
    app: tf-idf-worker
spec:
  type: NodePort
  selector:
    app: tf-idf-worker
  ports:
  - protocol: TCP
    port: 4002
    targetPort: 4002
    nodePort: 30002